;;(setq initial-buffer-choice "~/.emacs.d/init.el")
;;(setq initial-buffer-choice "~/dev/")
;;(setq initial-buffer-choice "~/dev/platz/frontend/src/components/GoogledLyricsSource.tsx")
;;(setq initial-buffer-choice "~/dev/platz/extension/platz-browser-extension/src/ScrapeGoogledLyricsContentScript.tsx")
;;(setq initial-buffer-choice "~/dev/crossword-project/cws/lib/http_client.ml")
;; (setq initial-buffer-choice "~/.emacs.d/startup.el")
;; (setq initial-buffer-choice "~/dev/org/org_server/lib/controller.ml")
;; (setq initial-buffer-choice "/Users/leo/dev/ocaml-playground/debugging_test/fib.ml")
;; (setq initial-buffer-choice "/Users/leo/dev/research-buddy/monolith/app.py")
(setq initial-buffer-choice (lambda () (get-buffer "*Messages*")))
