;;(setq initial-buffer-choice "~/.emacs.d/init.el")
;(setq initial-buffer-choice "~/dev/")
(setq initial-buffer-choice "~/dev/platz/frontend/src/components/GoogledLyricsSource.tsx")
;(setq initial-buffer-choice "~/dev/platz/extension/platz-browser-extension/src/ScrapeGoogledLyricsContentScript.tsx")
;(setq initial-buffer-choice "~/dev/crossword-project/cws/lib/http_client.ml")
